/* eslint-disable */
export default async () => {
    const t = {
        ["./enums/genre.enum"]: await import("./enums/genre.enum"),
        ["./modules/actors/entities/actor.entity"]: await import("./modules/actors/entities/actor.entity"),
        ["./modules/movies/entities/movie.entity"]: await import("./modules/movies/entities/movie.entity"),
        ["./modules/actors/dto/create-actor.dto"]: await import("./modules/actors/dto/create-actor.dto")
    };
    return { "@nestjs/swagger": { "models": [[import("./modules/movies/entities/movie.entity"), { "MoviesEntity": { idMovies: { required: false, type: () => Number }, title: { required: true, type: () => String }, genre: { required: true, enum: t["./enums/genre.enum"].GenreMoviesEnum }, imagePreview: { required: true, type: () => String }, synopsis: { required: true, type: () => String }, actors: { required: false, type: () => [t["./modules/actors/entities/actor.entity"].ActorsEntity] } } }], [import("./modules/actors/entities/actor.entity"), { "ActorsEntity": { idActors: { required: true, type: () => Number }, idMovies: { required: true, type: () => Number }, name: { required: true, type: () => String }, movies: { required: false, type: () => t["./modules/movies/entities/movie.entity"].MoviesEntity } } }], [import("./modules/actors/dto/actors.dto"), { "ActorsDto": { idActors: { required: true, type: () => Number }, idMovies: { required: true, type: () => Number }, name: { required: true, type: () => String } } }], [import("./modules/actors/dto/create-actor.dto"), { "CreateActorDto": { idActors: { required: true, type: () => Number }, idMovies: { required: true, type: () => Number }, name: { required: true, type: () => String } } }], [import("./modules/actors/dto/update-actor.dto"), { "UpdateActorDto": { name: { required: true, type: () => String } } }], [import("./modules/movies/dto/movie.dto"), { "MovieDto": { idMovies: { required: false, type: () => Number }, title: { required: true, type: () => String }, genre: { required: true, enum: t["./enums/genre.enum"].GenreMoviesEnum }, imagePreview: { required: true, type: () => String }, synopsis: { required: true, type: () => String }, actors: { required: false, type: () => [t["./modules/actors/dto/create-actor.dto"].CreateActorDto] } } }], [import("./modules/movies/dto/create-movie.dto"), { "CreateMovieDto": { idMovies: { required: false, type: () => Number }, title: { required: true, type: () => String }, genre: { required: true, enum: t["./enums/genre.enum"].GenreMoviesEnum }, synopsis: { required: true, type: () => String }, actors: { required: true, type: () => [t["./modules/actors/dto/create-actor.dto"].CreateActorDto] } } }], [import("./modules/movies/dto/update-movie.dto"), { "UpdateMovieDto": { genre: { required: true, enum: t["./enums/genre.enum"].GenreMoviesEnum }, imagePreview: { required: true, type: () => String }, title: { required: true, type: () => String }, synopsis: { required: true, type: () => String } } }]], "controllers": [[import("./modules/actors/actors.controller"), { "ActorsController": { "create": {}, "findAll": {}, "findOne": {}, "findByMovie": {}, "update": {}, "remove": {} } }], [import("./modules/movies/movies.controller"), { "MoviesController": { "create": {}, "findAll": {}, "findOne": {}, "findOneAndActors": {}, "update": {}, "remove": {} } }]] } };
};